profiles:
  active: dev
server:
  port: 9997
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ### useSSL=true 需要开启mysql端的ssl认证，后期需要再做
    url: jdbc:mysql://127.0.0.1:3306/msb_dongbao_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    schema:
    username: msb_dongbao_test
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 50
    minIdle: 5
    maxActive: 100
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 10000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j

  ### Redis配置
  redis:
    database: 0
    host: 39.103.132.33
    port: 6379
    timeout: 3600
    #jedis客户端
    jedis:
      pool:
        max-active: 500
        max-total: 500
        max-wait: -1
        min-idle: 20
        max-idle: 50
# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/msb/dongbao/*/db/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.msb.dongbao.pms.model.entity,com.msb.dongbao.pay.model.entity
  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #mybatis-plus.global-config.capital-mode=true
    #序列接口实现类配置
    #mybatis-plus.global-config.key-generator=com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  markdowns: classpath:markdown2x/*
  basic:
    enable: false
    username: zhangsan
    password: 123456
logging:
  config: classpath:logback-config.xml
  level:
    root: INFO